<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_order  = $block->getOrder();
    $_source = $block->getSource();
?>
<?php if ($_source->getCustomerBalanceAmount()): ?>
<tr style="padding: 0px;">
    <th <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> class="col name"  align="left">
        <strong><?php /* @escapeNotVerified */ echo __('Wallet'); ?></strong>
    </th>
    <td  align="right" <?php /* @escapeNotVerified */ echo $block->getValueProperties()?> class="col price"><span class="balance discount"><strong>-<?php /* @escapeNotVerified */ echo $_order->formatPrice($_source->getCustomerBalanceAmount()) ?></strong></span></td>
</tr>
<?php endif; ?>
